const CONTEXT_NAME = 'CLIENT'

const actions = {
    CLIENT_DEL: `${CONTEXT_NAME}_DEL`,
    CLIENT_GET_LIST: `${CONTEXT_NAME}_GET_LIST`,
    CLIENT_GET_SINGLE: `${CONTEXT_NAME}_GET_SINGLE`,
    CLIENT_REQUEST_DEL: `${CONTEXT_NAME}_REQUEST_DEL`,
    CLIENT_REQUEST_GET_LIST: `${CONTEXT_NAME}_REQUEST_GET_LIST`,
    CLIENT_REQUEST_GET_SINGLE: `${CONTEXT_NAME}_REQUEST_GET_SINGLE`,
    CLIENT_REQUEST_RESET: `${CONTEXT_NAME}_REQUEST_RESET`,
    CLIENT_REQUEST_SAVE_DATA: `${CONTEXT_NAME}_REQUEST_SAVE_DATA`,
    CLIENT_REQUEST_SEARCH: `${CONTEXT_NAME}_REQUEST_SEARCH`,
    CLIENT_RESET: `${CONTEXT_NAME}_RESET`,
    CLIENT_SAVE_DATA: `${CONTEXT_NAME}_SAVE_DATA`,
    CLIENT_SEARCH: `${CONTEXT_NAME}_SEARCH`
}

export { actions }
