const CONTEXT_NAME = 'HOTEL'

const actions = {
    HOTEL_DEL: `${CONTEXT_NAME}_DEL`,
    HOTEL_GET_SINGLE: `${CONTEXT_NAME}_GET_SINGLE`,
    HOTEL_REQUEST_DEL: `${CONTEXT_NAME}_REQUEST_DEL`,
    HOTEL_REQUEST_GET_SINGLE: `${CONTEXT_NAME}_REQUEST_GET_SINGLE`,
    HOTEL_REQUEST_SAVE_DATA: `${CONTEXT_NAME}_REQUEST_SAVE_DATA`,
    HOTEL_SAVE_DATA: `${CONTEXT_NAME}_SAVE_DATA`
}

export { actions }
