const CONTEXT_NAME = 'AGENCY'

const actions = {
    AGENCY_GET_LIST: `${CONTEXT_NAME}_GET_LIST`,
    AGENCY_GET_SINGLE: `${CONTEXT_NAME}_GET_SINGLE`,
    AGENCY_REQUEST_GET_LIST: `${CONTEXT_NAME}_REQUEST_GET_LIST`,
    AGENCY_REQUEST_GET_SINGLE: `${CONTEXT_NAME}_REQUEST_GET_SINGLE`,
    AGENCY_REQUEST_RESET: `${CONTEXT_NAME}_REQUEST_RESET`,
    AGENCY_REQUEST_SAVE_DATA: `${CONTEXT_NAME}_REQUEST_SAVE_DATA`,
    AGENCY_REQUEST_SEARCH: `${CONTEXT_NAME}_REQUEST_SEARCH`,
    AGENCY_RESET: `${CONTEXT_NAME}_RESET`,
    AGENCY_SAVE_DATA: `${CONTEXT_NAME}_SAVE_DATA`,
    AGENCY_SEARCH: `${CONTEXT_NAME}_SEARCH`
}

export { actions }
