const CONTEXT_NAME = 'TIP'

const actions = {
    TIP_DEL: `${CONTEXT_NAME}_DEL`,
    TIP_DEL_LIBRARY: `${CONTEXT_NAME}_DEL_LIBRARY`,
    TIP_FILTER: `${CONTEXT_NAME}_FILTER`,
    TIP_GET_CATEGORY: `${CONTEXT_NAME}_GET_CATEGORY`,
    TIP_GET_LIST: `${CONTEXT_NAME}_GET_LIST`,
    TIP_GET_SINGLE: `${CONTEXT_NAME}_GET_SINGLE`,
    TIP_REQUEST_DEL: `${CONTEXT_NAME}_REQUEST_DEL`,
    TIP_REQUEST_DEL_LIBRARY: `${CONTEXT_NAME}_REQUEST_DEL_LIBRARY`,
    TIP_REQUEST_FILTER: `${CONTEXT_NAME}_REQUEST_FILTER`,
    TIP_REQUEST_GET_CATEGORY: `${CONTEXT_NAME}_REQUEST_GET_CATEGORY`,
    TIP_REQUEST_GET_LIST: `${CONTEXT_NAME}_REQUEST_GET_LIST`,
    TIP_REQUEST_GET_SINGLE: `${CONTEXT_NAME}_REQUEST_GET_SINGLE`,
    TIP_REQUEST_SAVE_DATA: `${CONTEXT_NAME}_REQUEST_SAVE_DATA`,
    TIP_REQUEST_SET_OBJ: `${CONTEXT_NAME}_REQUEST_SET_OBJ`,
    TIP_SAVE_DATA: `${CONTEXT_NAME}_SAVE_DATA`,
    TIP_SET_OBJ: `${CONTEXT_NAME}_SET_OBJ`
}

const categoriesTypes = ['events', 'gastronomy', 'nightlife', 'shopping', 'tour']
export { actions, categoriesTypes }
