const CONTEXT_NAME = 'TRANSFER'
const actions = {
    TRANSFER_DEL: `${CONTEXT_NAME}_DEL`,
    TRANSFER_EDIT: `${CONTEXT_NAME}_EDIT`,
    TRANSFER_GET_SINGLE: `${CONTEXT_NAME}_GET_SINGLE`,
    TRANSFER_REQUEST_DEL: `${CONTEXT_NAME}_REQUEST_DEL`,
    TRANSFER_REQUEST_EDIT: `${CONTEXT_NAME}_REQUEST_EDIT`,
    TRANSFER_REQUEST_GET_SINGLE: `${CONTEXT_NAME}_REQUEST_GET_SINGLE`,
    TRANSFER_REQUEST_SAVE_DATA: `${CONTEXT_NAME}_REQUEST_SAVE_DATA`,
    TRANSFER_SAVE_DATA: `${CONTEXT_NAME}_SAVE_DATA`
}

export { actions }
