const CONTEXT_NAME = 'TASKS'

const actions = {
    TASKS_DEL: `${CONTEXT_NAME}_DEL`,
    TASKS_GET_ALL: `${CONTEXT_NAME}_GET_ALL`,
    TASKS_REQUEST_DEL: `${CONTEXT_NAME}_REQUEST_DEL`,
    TASKS_REQUEST_GET_ALL: `${CONTEXT_NAME}_REQUEST_GET_ALL`,
    TASKS_REQUEST_SAVE_DATA: `${CONTEXT_NAME}_REQUEST_SAVE_DATA`,
    TASKS_SAVE_DATA: `${CONTEXT_NAME}_SAVE_DATA`
}

export { actions }
