const CONTEXT_NAME = 'TOUR'

const actions = {
    TOUR_DEL: `${CONTEXT_NAME}_DEL`,
    TOUR_GET_SINGLE: `${CONTEXT_NAME}_GET_SINGLE`,
    TOUR_REQUEST_DEL: `${CONTEXT_NAME}_REQUEST_DEL`,
    TOUR_REQUEST_GET_SINGLE: `${CONTEXT_NAME}_REQUEST_GET_SINGLE`,
    TOUR_REQUEST_SAVE_DATA: `${CONTEXT_NAME}_REQUEST_SAVE_DATA`,
    TOUR_SAVE_DATA: `${CONTEXT_NAME}_SAVE_DATA`
}

export { actions }
