const cuisineTypes = [
    'Argentina',
    'Asiatica',
    'Creole',
    'Indiana',
    'Libanesa',
    'Otomana',
    'Tailandesa',
    'Vegetariana',
    'Fusao',
    'Alema',
    'Brasileira',
    'Espanhola',
    'Inglesa',
    'Marroquina',
    'Peruana',
    'Vietnamita',
    'Internacional',
    'Americana',
    'Chinesa',
    'Francesa',
    'Italiana',
    'Mediterranea',
    'Pizzaria',
    'FrutosDoMar',
    'TipicaLocal',
    'Arabe',
    'Coreana',
    'Grega',
    'Japonesa',
    'Mexicana',
    'Portuguesa',
    'Contemporanea'
]

export { cuisineTypes }
