const events = {
    CHANGE_BRAND: 'CHANGE_BRAND',
    CHANGE_THEME: 'CHANGE_THEME',
    FORM_RESET: 'FORM_RESET',
    OPEN_MODAL: 'OPEN_MODAL',
    SERVICE_DELETED: 'SERVICE_DELETED',
    SORT_TABLE: 'SORT_TABLE',
    UPDATE_IMAGE: 'UPDATE_IMAGE'
}

export { events }
