const CONTEXT_NAME = 'TRAVEL_SCRIPT'

const actions = {
    TRAVEL_SCRIPT_CLOSE_MATERIAL: `${CONTEXT_NAME}_CLOSE_MATERIAL`,
    TRAVEL_SCRIPT_DEL_SERVICE: `${CONTEXT_NAME}_DEL_SERVICE`,
    TRAVEL_SCRIPT_GET_SINGLE: `${CONTEXT_NAME}_GET_SINGLE`,
    TRAVEL_SCRIPT_REQUEST_CLOSE_MATERIAL: `${CONTEXT_NAME}_REQUEST_CLOSE_MATERIAL`,
    TRAVEL_SCRIPT_REQUEST_DEL_SERVICE: `${CONTEXT_NAME}_REQUEST_DEL_SERVICE`,
    TRAVEL_SCRIPT_REQUEST_GET_SINGLE: `${CONTEXT_NAME}_REQUEST_GET_SINGLE`,
    TRAVEL_SCRIPT_REQUEST_SHARE: `${CONTEXT_NAME}_REQUEST_SHARE`,
    TRAVEL_SCRIPT_REQUEST_UNSHARE: `${CONTEXT_NAME}_REQUEST_UNSHARE`,
    TRAVEL_SCRIPT_REQUEST_UPDATE_CITY: `${CONTEXT_NAME}_REQUEST_UPDATE_CITY`,
    TRAVEL_SCRIPT_REQUEST_UPDATE_MATERIAL: `${CONTEXT_NAME}_REQUEST_UPDATE_MATERIAL`,
    TRAVEL_SCRIPT_SHARE: `${CONTEXT_NAME}_SHARE`,
    TRAVEL_SCRIPT_UNSHARE: `${CONTEXT_NAME}_UNSHARE`,
    TRAVEL_SCRIPT_UPDATE_CITY: `${CONTEXT_NAME}_UPDATE_CITY`,
    TRAVEL_SCRIPT_UPDATE_MATERIAL: `${CONTEXT_NAME}_UPDATE_MATERIAL`
}

export { actions }
