const CONTEXT_NAME = 'CRUISE'

const actions = {
    CRUISE_DEL: `${CONTEXT_NAME}_DEL`,
    CRUISE_GET_SINGLE: `${CONTEXT_NAME}_GET_SINGLE`,
    CRUISE_REQUEST_DEL: `${CONTEXT_NAME}_REQUEST_DEL`,
    CRUISE_REQUEST_GET_SINGLE: `${CONTEXT_NAME}_REQUEST_GET_SINGLE`,
    CRUISE_REQUEST_SAVE_DATA: `${CONTEXT_NAME}_REQUEST_SAVE_DATA`,
    CRUISE_SAVE_DATA: `${CONTEXT_NAME}_SAVE_DATA`
}

export { actions }
