const CONTEXT_NAME = 'AERIAL'

const actions = {
    AERIAL_DEL: `${CONTEXT_NAME}_DEL`,
    AERIAL_GET_SINGLE: `${CONTEXT_NAME}_GET_SINGLE`,
    AERIAL_REQUEST_DEL: `${CONTEXT_NAME}_REQUEST_DEL`,
    AERIAL_REQUEST_GET_SINGLE: `${CONTEXT_NAME}_REQUEST_GET_SINGLE`,
    AERIAL_REQUEST_SAVE_DATA: `${CONTEXT_NAME}_REQUEST_SAVE_DATA`,
    AERIAL_SAVE_DATA: `${CONTEXT_NAME}_SAVE_DATA`
}

export { actions }
