const CONTEXT_NAME = 'CONSULTANT'

const actions = {
    CONSULTANT_DEL: `${CONTEXT_NAME}_DEL`,
    CONSULTANT_GET_LIST: `${CONTEXT_NAME}_GET_LIST`,
    CONSULTANT_GET_SINGLE: `${CONTEXT_NAME}_GET_SINGLE`,
    CONSULTANT_REQUEST_DEL: `${CONTEXT_NAME}_REQUEST_DEL`,
    CONSULTANT_REQUEST_GET_LIST: `${CONTEXT_NAME}_REQUEST_GET_LIST`,
    CONSULTANT_REQUEST_GET_SINGLE: `${CONTEXT_NAME}_REQUEST_GET_SINGLE`,
    CONSULTANT_REQUEST_RESET: `${CONTEXT_NAME}_REQUEST_RESET`,
    CONSULTANT_REQUEST_SAVE_DATA: `${CONTEXT_NAME}_REQUEST_SAVE_DATA`,
    CONSULTANT_REQUEST_SEARCH: `${CONTEXT_NAME}_REQUEST_SEARCH`,
    CONSULTANT_RESET: `${CONTEXT_NAME}_RESET`,
    CONSULTANT_SAVE_DATA: `${CONTEXT_NAME}_SAVE_DATA`,
    CONSULTANT_SEARCH: `${CONTEXT_NAME}_SEARCH`
}

const statusColors = {
    BLOCKED: '#dd6876',
    RELEASED: '#76dd68'
}

export { actions, statusColors }
