const CONTEXT_NAME = 'TRAVEL'

const actions = {
    TRAVEL_ARCHIVE: `${CONTEXT_NAME}_ARCHIVE`,
    TRAVEL_DEL: `${CONTEXT_NAME}_DEL`,
    TRAVEL_EDIT: `${CONTEXT_NAME}_EDIT`,
    TRAVEL_GET_ARCHIVEDS: `${CONTEXT_NAME}_GET_ARCHIVEDS`,
    TRAVEL_GET_LIST: `${CONTEXT_NAME}_GET_LIST`,
    TRAVEL_REQUEST_ARCHIVE: `${CONTEXT_NAME}_REQUEST_ARCHIVE`,
    TRAVEL_REQUEST_DEL: `${CONTEXT_NAME}_REQUEST_DEL`,
    TRAVEL_REQUEST_EDIT: `${CONTEXT_NAME}_REQUEST_EDIT`,
    TRAVEL_REQUEST_GET_ARCHIVEDS: `${CONTEXT_NAME}_REQUEST_GET_ARCHIVEDS`,
    TRAVEL_REQUEST_GET_LIST: `${CONTEXT_NAME}_REQUEST_GET_LIST`,
    TRAVEL_REQUEST_RESET: `${CONTEXT_NAME}_REQUEST_RESET`,
    TRAVEL_REQUEST_SAVE_DATA: `${CONTEXT_NAME}_REQUEST_SAVE_DATA`,
    TRAVEL_REQUEST_SEARCH: `${CONTEXT_NAME}_REQUEST_SEARCH`,
    TRAVEL_REQUEST_SEARCH_CITY_GOOGLE_API: `${CONTEXT_NAME}_REQUEST_SEARCH_CITY_GOOGLE_API`,
    TRAVEL_REQUEST_SEARCH_CITY_OUR_API: `${CONTEXT_NAME}_REQUEST_SEARCH_CITY_OUR_API`,
    TRAVEL_REQUEST_SEARCH_CLIENTS: `${CONTEXT_NAME}_REQUEST_SEARCH_CLIENTS`,
    TRAVEL_REQUEST_UNARCHIVE: `${CONTEXT_NAME}_REQUEST_UNARCHIVE`,
    TRAVEL_RESET: `${CONTEXT_NAME}_RESET`,
    TRAVEL_RESET_SUGGESTIONS: `${CONTEXT_NAME}_RESET_SUGGESTIONS`,
    TRAVEL_SAVE_DATA: `${CONTEXT_NAME}_SAVE_DATA`,
    TRAVEL_SEARCH: `${CONTEXT_NAME}_SEARCH`,
    TRAVEL_SEARCH_CITY_GOOGLE_API: `${CONTEXT_NAME}_SEARCH_CITY_GOOGLE_API`,
    TRAVEL_SEARCH_CITY_OUR_API: `${CONTEXT_NAME}_SEARCH_CITY_OUR_API`,
    TRAVEL_SEARCH_CLIENTS: `${CONTEXT_NAME}_SEARCH_CLIENTS`,
    TRAVEL_UNARCHIVE: `${CONTEXT_NAME}_UNARCHIVE`
}

const travelStatusColors = {
    ARCHIVED: '#adadab',
    BOARDING_NEAR: '#dddd68',
    CONCLUDED: '#cfd0cd',
    PENDING: '#dd6876',
    SENT: '#c2dd68',
    TRAVELING: '#76dd68'
}

export { actions, travelStatusColors }
