const CONTEXT_NAME = 'PROGRAMMING'

const actions = {
    PROGRAMMING_DEL: `${CONTEXT_NAME}_DEL`,
    PROGRAMMING_GET_SINGLE: `${CONTEXT_NAME}_GET_SINGLE`,
    PROGRAMMING_REQUEST_DEL: `${CONTEXT_NAME}_REQUEST_DEL`,
    PROGRAMMING_REQUEST_GET_SINGLE: `${CONTEXT_NAME}_REQUEST_GET_SINGLE`,
    PROGRAMMING_REQUEST_SAVE_DATA: `${CONTEXT_NAME}_REQUEST_SAVE_DATA`,
    PROGRAMMING_SAVE_DATA: `${CONTEXT_NAME}_SAVE_DATA`
}

export { actions }
