const CONTEXT_NAME = 'CAR_RENTAL'

const actions = {
    CAR_RENTAL_DEL: `${CONTEXT_NAME}_DEL`,
    CAR_RENTAL_GET_SINGLE: `${CONTEXT_NAME}_GET_SINGLE`,
    CAR_RENTAL_REQUEST_DEL: `${CONTEXT_NAME}_REQUEST_DEL`,
    CAR_RENTAL_REQUEST_GET_SINGLE: `${CONTEXT_NAME}_REQUEST_GET_SINGLE`,
    CAR_RENTAL_REQUEST_SAVE_DATA: `${CONTEXT_NAME}_REQUEST_SAVE_DATA`,
    CAR_RENTAL_SAVE_DATA: `${CONTEXT_NAME}_SAVE_DATA`
}

export { actions }
