const CONTEXT_NAME = 'NEW_AGENCY'

const actions = {
    NEW_AGENCY_DEL: `${CONTEXT_NAME}_DEL`,
    NEW_AGENCY_GET_LIST: `${CONTEXT_NAME}_GET_LIST`,
    NEW_AGENCY_GET_SINGLE: `${CONTEXT_NAME}_GET_SINGLE`,
    NEW_AGENCY_REQUEST_DEL: ` ${CONTEXT_NAME}_REQUEST_DEL`,
    NEW_AGENCY_REQUEST_GET_LIST: `${CONTEXT_NAME}_REQUEST_GET_LIST`,
    NEW_AGENCY_REQUEST_GET_SINGLE: `${CONTEXT_NAME}_REQUEST_GET_SINGLE`,
    NEW_AGENCY_REQUEST_RESET: `${CONTEXT_NAME}_REQUEST_RESET`,
    NEW_AGENCY_REQUEST_SAVE_DATA: `${CONTEXT_NAME}_REQUEST_SAVE_DATA`,
    NEW_AGENCY_REQUEST_SEARCH: `${CONTEXT_NAME}_REQUEST_SEARCH`,
    NEW_AGENCY_RESET: `${CONTEXT_NAME}_RESET`,
    NEW_AGENCY_SAVE_DATA: `${CONTEXT_NAME}_SAVE_DATA`,
    NEW_AGENCY_SEARCH: `${CONTEXT_NAME}_SEARCH`
}

const statusColors = {
    BLOCKED: '#dd6876',
    RELEASED: '#76dd68'
}

export { actions, statusColors }
