const CONTEXT_NAME = 'RESTAURANT'

const actions = {
    RESTAURANT_DEL: `${CONTEXT_NAME}_DEL`,
    RESTAURANT_GET_SINGLE: `${CONTEXT_NAME}_GET_SINGLE`,
    RESTAURANT_REQUEST_DEL: `${CONTEXT_NAME}_REQUEST_DEL`,
    RESTAURANT_REQUEST_GET_SINGLE: `${CONTEXT_NAME}_REQUEST_GET_SINGLE`,
    RESTAURANT_REQUEST_SAVE_DATA: `${CONTEXT_NAME}_REQUEST_SAVE_DATA`,
    RESTAURANT_SAVE_DATA: `${CONTEXT_NAME}_SAVE_DATA`
}

export { actions }
