const CONTEXT_NAME = 'TRAIN'

const actions = {
    TRAIN_DEL: `${CONTEXT_NAME}_DEL`,
    TRAIN_EDIT: `${CONTEXT_NAME}_EDIT`,
    TRAIN_GET_LIST: `${CONTEXT_NAME}_GET_LIST`,
    TRAIN_GET_SINGLE: `${CONTEXT_NAME}_GET_SINGLE`,
    TRAIN_REQUEST_DEL: `${CONTEXT_NAME}_REQUEST_DEL`,
    TRAIN_REQUEST_GET_SINGLE: `${CONTEXT_NAME}_REQUEST_GET_SINGLE`,
    TRAIN_REQUEST_SAVE_DATA: `${CONTEXT_NAME}_REQUEST_SAVE_DATA`,
    TRAIN_REQUEST_SEARCH: `${CONTEXT_NAME}_REQUEST_SEARCH`,
    TRAIN_SAVE_DATA: `${CONTEXT_NAME}_SAVE_DATA`,
    TRAIN_SEARCH: `${CONTEXT_NAME}_SEARCH`
}

export { actions }
